processing.config:
  processing.path:
    sketches:
      - "template_circle"
      - "template_letters"
      - "template_line"

  bot.config:
    reddit_subreddit:
      - "art"
      - "pics"
      - "itookapicture"
      - "earthporn"


  imgur.config:
    imgur_client_id: ""
    imgur_app_secret: ""
    imgur_access_token: ""

  reddit.config:
    reddit_app_username: ""
    reddit_app_password: ""
    reddit_client_id: ""
    reddit_app_secret: ""
