proccesing.config:
  processing.path:
    java.path: ''
    sketch.path: ''

  bot.config:
    reddit_subreddit: "pics"
    interval-seconds: 7200


  imgur.config:
    imgur_client_id: "e6158b5ee68c0c2"
    imgur_app_secret: "c03e62fe1f0fa1f721bbee211638944ff7d96ac9"
    imgur_access_token: ""

  reddit.config:
    reddit_app_username: "jarmahent"
    reddit_app_password: "kilo0131"
    reddit_client_id: "TEIR2LWIcoAb_A"
    reddit_app_secret: "LaONMBNb01V0ItUD3SjrmC4mI9M"
