proccesing.config:
  processing.path:
    java.path: ''
    sketch.path: ''

  bot.config:
    reddit_subreddit: "pics"
    interval-seconds: 7200


  imgur.config:
    imgur_client_id: ""
    imgur_app_secret: ""
    imgur_access_token: ""

  reddit.config:
    reddit_app_username: ""
    reddit_app_password: ""
    reddit_client_id: ""
    reddit_app_secret: ""
