processing.config:
  processing.path:
    sketches:
      - "template_circle"
      - "template_letters"
      - "template_line"

  bot.config:
    reddit_subreddit:
      - "art"
      - "pics"
      - "itookapicture"


  imgur.config:
    imgur_client_id: "e6158b5ee68c0c2"
    imgur_app_secret: "ace07385bb95e9cf63edb4e2374efac571815b49"
    imgur_access_token: ""

  reddit.config:
    reddit_app_username: "ProcessingImagesBot"
    reddit_app_password: "kilo0131"
    reddit_client_id: "ISPc2iqSWSzHmQ"
    reddit_app_secret: "54igoiMvmZzmv3QdkS0TmbDx4d0"
