processing.config:
  processing.path:
    java.path: ''
    sketch.path: ''
    sketches:
      - "template_circle"
      - "template_letters"

  bot.config:
    loop: True
    reddit_subreddit: "art"
    interval-seconds: 300


  imgur.config:
    imgur_client_id: "e6158b5ee68c0c2"
    imgur_app_secret: "00b195777805469ec376078589e45f1c0789441e"
    imgur_access_token: ""

  reddit.config:
    reddit_app_username: "ImageProcessingBot"
    reddit_app_password: "Laurh2335"
    reddit_client_id: "ISPc2iqSWSzHmQ"
    reddit_app_secret: "54igoiMvmZzmv3QdkS0TmbDx4d0"
