processing.config:
  processing.path:
    java.path: ''
    sketch.path: ''
    sketches:
      - "template_circle"
      - "template_letters"

  bot.config:
    loop: True
    reddit_subreddit: "art"
    interval-seconds: 30


  imgur.config:
    imgur_client_id: ""
    imgur_app_secret: ""
    imgur_access_token: ""

  reddit.config:
    reddit_app_username: ""
    reddit_app_password: ""
    reddit_client_id: ""
    reddit_app_secret: ""
